version: 2.1
orbs:
  win: circleci/windows@1.0.0
jobs:
  build-nix:
    docker:
      - image: 'python:3.7.3-stretch'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "requirements.txt" }}'
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install-nix
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: 'v1-dependencies-{{ checksum "requirements.txt" }}'
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint-nix

  build-win:
    executor:
      name: win/vs2019
      shell: bash.exe
    working_directory: ~/repo
    steps: 
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "requirements.txt" }}'
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            choco install python --version=3.7.2
            choco install docker-engine
            choco install make
            python -m venv venv
            . venv/bin/activate
            make install-win
      - save_cache:
          paths:
            - ./venv
          key: 'v1-dependencies-{{ checksum "requirements.txt" }}'
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint-win
          
workflows:
  build-all:
    jobs:
      - build-nix
      - build-win
      
